name: CI/CD Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Cada push a main dispara el workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker build -t mi-backend ./back-end
        docker build -t mi-frontend ./front-end
        

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_KEY }}
        script: |
          sudo docker stop mi-frontend-container || true
          sudo docker rm mi-frontend-container || true
          sudo docker stop mi-backend-container || true
          sudo docker rm mi-backend-container || true
          sudo docker run -d -p 5000:5000 --name mi-backend-container mi-backend
          sudo docker run -d -p 3000:80 --name mi-frontend-container mi-frontend

